Update scripts

diff --git a/.chezmoiscripts/run_onchange_after_00-sync-packages.sh.tmpl b/.chezmoiscripts/run_onchange_after_00-sync-packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange_after_00-sync-packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_after_00-sync-packages.sh.tmpl
@@ -1,22 +1,34 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-echo "📦 Running package sync task..."
+echo "🚀 Starting package sync..."
 
 {{ if eq .chezmoi.os "darwin" }}
 
 # {{ include "dot_Brewfile" | sha256sum }}
-
-eval "$(/opt/homebrew/bin/brew shellenv)"
-
-brew bundle --global
+if command -v /opt/homebrew/bin/brew > /dev/null 2>&1; then
+    echo "📦 Syncing Homebrew packages..."
+    eval "$(/opt/homebrew/bin/brew shellenv)"
+    brew bundle --global
+    echo "✅ Homebrew packages synced."
+else
+    echo "❌ Homebrew command not found..."
+    exit 1
+fi
 
 {{ else if eq .chezmoi.os "linux" }}
 
 # {{ include "private_dot_config/mise/mise.lock" | sha256sum }}
-
-eval "$(~/.local/bin/mise activate)"
-
-mise install
+if command -v mise > /dev/null 2>&1; then
+    echo "📦 Installing Mise..."
+    eval "$(~/.local/bin/mise activate)"
+    mise install
+    echo "✅ Mise packages synced."
+else
+    echo "❌ Mise command not found..."
+    exit 1
+fi
 
 {{ end }}
+
+echo "✅ Package sync complete!"
